apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- backend/deploy.yml
- backend/service.yml
- ingress.yml

images:
- name: dan1993/api-church
  newName: dan1993/api-church
  newTag: 09b32718eaf7dc0034017830f9e64a31af1a4fc7
