apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/users
spec:
  type: NodePort 
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 30000
